parameters:
    app.domain: '%env(APP_DOMAIN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    DataFixtures\:
        resource: '../fixtures/'
