parameters:
    app.domain: '%env(APP_DOMAIN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/Model/Entity/'
            - '../src/Kernel.php'

    # Third-party payment processors
    Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor: ~
    Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor: ~

    # DataFixtures
    DataFixtures\:
        resource: '../fixtures/'
